#! /bin/sh

die() {
    [ -n "$1" ] && echo >&2 "$1"
    cat >&2 <<EOF
Usage: $0 [-j JOBS] [-o DIRECTORY] FILE [FILE...]
Available options:
  -f            move mp4 index to beginning of file
  -j JOBS       number of jobs to run in parallel (default: 4)
  -o DIRECTORY  set output directory (default: \$PWD)
  -x OPTS       extra options to ffmpeg
EOF
    exit 1
}

process_file() {
    [ ! -f "$1" ] && echo "File not found: $1" && exit 1
    infile="$(basename "$1")"
    acodec=$(ffprobe -v error -i "$1" -show_streams -select_streams a:0 \
        -show_entries stream=codec_name:stream_tags=0:stream_disposition=0 \
        -of default=nokey=1:noprint_wrappers=1)
    [ "$acodec" = "aac" ] && opts="-c:a copy" || opts="-c:a libfdk_aac -ac 2 -vbr 5" 
    ffmpeg -v error -stats -i "$1" -c:v copy $opts $_XOPTS $_FASTSTART "$_OUTDIR/${infile%.*}.mp4"
    exit $?
}

[ -n "$_PROCESS" ] && process_file "$1"

JOBS=4
_OUTDIR="$PWD"
_PROCESS=1

while getopts ":fj:o:x:" opt; do
    case $opt in
        f)
            _FASTSTART="-movflags faststart"
            ;;
        j)
            [ ! "$OPTARG" -ge 0 2>/dev/null ] && die "Invalid number of jobs: $OPTARG"
            _JOBS="$OPTARG"
            ;;
        o)
            [ ! -d "$OPTARG" ] && die "Invalid directory: $OPTARG"
            _OUTDIR="$OPTARG"
            ;;
        x)
            _XOPTS="$OPTARG"
            ;;
        \?)
            die "Invalid option: -$opt"
            ;;
    esac
done

shift $((OPTIND - 1))
[ "$#" -eq 0 ] && die "No input files specified"

export _FASTSTART _OUTDIR _PROCESS _XOPTS 

for m; do printf '%s\0' "$m"; done | xargs -0 -n1 -P$JOBS -I{} $SHELL "$0" {}
